// Code generated by Slice Machine. DO NOT EDIT.

import EmceeList from './EmceeList/index.svelte';
import HeroText from './HeroText/index.svelte';
import LogoList from './LogoList/index.svelte';

export const components = {
	emcee_list: EmceeList,
	hero_text: HeroText,
	logo_list: LogoList
};
